server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/banking
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect   # ✅ ADD THIS

  kafka:
    bootstrap-servers: banking-redpanda:9092